// larvel-vue-inertia/resources/js/Components/Grid.vue
<template>
   <div
      class=" flex flex-col justify-between"
      :class="index % 3 === 0 ? 'col-span-2 aspect-video' : ''" 
   >
      <ImageContainer
         :url="artObject.webImage.url"
         :objectId="artObject.objectNumber"
      />
      <div class="mt-2 leading-4 flex justify-between items-center">
         <div class="flex flex-col">
            <p>{{artObject.title}}</p>
            <p class="text-xs">By <span class="text-accent">{{artObject.principalOrFirstMaker}}</span></p>
         </div>
         <a :href="artObject.links.web" target="_blank" rel="noopener noreferrer">
            <FiExternalLink class="text-accent cursor-pointer" />
         </a>
      </div>
   </div>
</template>

<script setup lang="ts">
import ImageContainer from "./ImageContainer.vue"

export interface GridProps {
   artObject: ArtObjectType
   index: number
}

defineProps<GridProps>()
</script>

// nextjs-12/src/components/Grid.tsx
import { FC } from "react"
import { FiExternalLink } from "react-icons/fi"
import { ImageContainer } from "./ImageContainer"

interface GridProps {
   artObject: ArtObjectType
   index: number
}

export const Grid:FC<GridProps> = ({
   index,
   artObject
}) => {
   
   return (
      <div
         className={`${index % 3 === 0 ? "col-span-2 aspect-video" : ""} flex flex-col justify-between`}
      >
         <ImageContainer 
            url={artObject.webImage.url}
            objectId={artObject.objectNumber}
         />
         <div className="mt-2 leading-4 flex justify-between items-center">
            <div className="flex flex-col">
               <p>{artObject.title}</p>
               <p className="text-xs">By <span className="text-accent">{artObject.principalOrFirstMaker}</span></p>
            </div>
            <a href={artObject.links.web} target="_blank" rel="noopener noreferrer">
               <FiExternalLink className="text-accent cursor-pointer" size={16} />
            </a>
         </div>
      </div>
   )
}
