// vue3/src/components/ImageContainer.vue
<template>
   <div 
      className="w-full h-full"
      v-if="disableLink"
   >
      <img 
         className="h-full w-full object-cover" 
         :src="url" 
         alt="Artwork" 
      />
   </div>
   <RouterLink
      v-else
      class="w-full h-full relative overflow-hidden group"
      :to="{
         name: 'Detail',
         params: {
            id: objectId
         }
      }"
   >
      <img 
         class="h-full w-full object-cover" 
         :src="url"
         alt="Artwork" 
      />
      <div class="absolute opacity-0 duration-300 group-hover:opacity-100 inset-0 bg-contrast/40 text-accent flex items-center justify-center">
         <h3 class="text-2xl scale-150 group-hover:scale-100  duration-300 font-display">Read more</h3>
      </div>
   </RouterLink>
</template>

<script setup lang="ts">
import { RouterLink } from "vue-router"
export interface Props {
   url: string
   objectId: string
   disableLink?: boolean
}

defineProps<Props>()
</script>

// nextjs-12/src/components/ImageContainer.tsx
import { playfair } from "@/utils/fonts"
import clsx from "clsx"
import Link from "next/link"
import { FC } from "react"

export const ImageContainer:FC<{
   url: string
   objectId: string
   disableLink?: boolean
}> = ({
   url,
   objectId,
   disableLink = false
}) => {
   if(disableLink){
      return (
         <div className="w-full h-full">
            <img 
               className="h-full w-full object-cover" 
               src={url} 
               alt="Artwork" 
            />
         </div>
      )
   }

   return (
      <Link 
         className="w-full h-full relative overflow-hidden group"
         href={`/artwork/${objectId}`}
      >
         <img 
            className="h-full w-full object-cover" 
            src={url} 
            alt="Artwork" 
         />
         <div className="absolute opacity-0 duration-300 group-hover:opacity-100 inset-0 bg-contrast/70 text-accent flex items-center justify-center">
            <h3 className={clsx("text-2xl scale-150 group-hover:scale-100  duration-300", playfair.className)}>Read more</h3>
         </div>
      </Link>
   )
}
