// nextjs-13/src/components/Hero.tsx
"use client"
import { playfair } from "@/utils/fonts"
import { FC } from "react"
import { FiExternalLink } from "react-icons/fi"
import { ImageContainer } from "./ImageContainer"
import { useParams } from "next/navigation"

interface HeroProps {
   artObject: ArtObjectType
}

export const Hero:FC<HeroProps> = ({
   artObject
}) => {
   const titleSplitted = artObject.title.split(" ")
   const lowerAmount =  Math.floor(titleSplitted.length / 3) 
   const higherAmount =  Math.ceil(titleSplitted.length / 3)
   const params = useParams()

   return (
      <div className="grid grid-cols-1 md:grid-cols-2 relative">
         <div className="transform bottom-2 bg-contrast/60 backdrop-blur p-4 rounded absolute md:relative md:bg-transparent md:backdrop-blur-0 translate-x-[10%] my-auto flex flex-col items-start">
            <h2 className={`text-2xl md:text-5xl lg:text-7xl ${playfair.className} flex flex-col items-start gap-2`}>
               <span className="border-t-2 border-primary">
                  {[...titleSplitted].splice(0, lowerAmount).join(" ")}
               </span>
               <span className="transform translate-x-[5%] border-y-2 border-primary">
                  {[...titleSplitted].splice(lowerAmount, higherAmount).join(" ")}
               </span>
               <span className="border-b-2 border-primary">
                  {[...titleSplitted].splice(lowerAmount + higherAmount).join(" ")}
               </span>
            </h2>
            <p className="mt-6">By <span className="text-accent font-bold">{artObject.principalOrFirstMaker}</span></p>
            <p className="text-accent italic">
               <a href={artObject.links.web} target="_blank" className="flex gap-2 items-center">
                  Link to rijksmuseum <FiExternalLink size={16} />
               </a>
            </p>
         </div>
         <div className="aspect-square">
            <ImageContainer 
               url={artObject.webImage.url}
               objectId={artObject.objectNumber}
               disableLink={!!params.id}
            />
         </div>
      </div>
   )
}

// larvel-vue-inertia/resources/js/Components/Hero.vue
<template>
   <div class="grid grid-cols-1 md:grid-cols-2 relative">
      <div class="transform bottom-2 bg-contrast/60 backdrop-blur p-4 rounded absolute md:relative md:bg-transparent md:backdrop-blur-0 translate-x-[10%] my-auto flex flex-col items-start z-40">
         <h2 class="text-2xl md:text-5xl lg:text-7xl font-display flex flex-col items-start gap-2">
            <span class="border-t-2 border-primary">
               {{[...titleSplitted].splice(0, lowerAmount).join(" ")}}
            </span>
            <span class="transform translate-x-[5%] border-y-2 border-primary">
               {{[...titleSplitted].splice(lowerAmount, higherAmount).join(" ")}}
            </span>
            <span class="border-b-2 border-primary">
               {{[...titleSplitted].splice(lowerAmount + higherAmount).join(" ")}}
            </span>
         </h2>
         <p class="mt-6">By <span class="text-accent font-bold">{{artObject.principalOrFirstMaker}}</span></p>
         <p class="text-accent italic">
            <a :href="artObject.links.web" target="_blank" class="flex gap-2 items-center">
               Link to rijksmuseum <FiExternalLink />
            </a>
         </p>
      </div>
      <div class="aspect-square">
         <!-- <ImageContainer
            :url="artObject.webImage.url"
            :objectId="artObject.objectNumber"
            :disableLink="!!route.params.id"
         /> -->
      </div>
   </div>
</template>

<script setup lang="ts">
import ImageContainer from "./ImageContainer.vue"

export interface HeroProps {
   artObject: ArtObjectType
}

const props = defineProps<HeroProps>()
const titleSplitted = props.artObject.title.split(" ")
const lowerAmount =  Math.floor(titleSplitted.length / 3) 
const higherAmount =  Math.ceil(titleSplitted.length / 3)
</script>
